version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
  db:
    image: postgres:15.1-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
  app:
    build:
      dockerfile: ./Dockerfile
    container_name: app
    external_links:
      - db:db
      - redis:redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    command:
      - uvicorn
      - menu_app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
    restart: always
