version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
  db:
    image: postgres:15.1-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
  rabbitmq:
    image: rabbitmq:3.12.2-management-alpine
    container_name: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
  app:
    build:
      dockerfile: ./Dockerfile
    container_name: app
    external_links:
      - "db:db"
      - "redis:redis"
    ports:
      - "8000:8000"
    env_file:
      - .env
    command:
      - uvicorn
      - menu_app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
    volumes:
      - ${PWD}/admin:/app/menu_app/admin
    restart: always
  celery:
    build:
      context: .
    container_name: celery
    env_file:
      - .env
    external_links:
      - "rabbitmq:rabbitmq"
      - "app:app"
    command:
      - celery
      - --app=menu_app.worker:celery
      - worker
      - -B
      - -l
      - INFO
    restart: always
    volumes:
      - ${PWD}/admin:/app/menu_app/admin
