version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    networks:
      - ylabnetwork
    env_file:
      - .env
    ports:
      - "6379:6379"
  db:
    image: postgres:15.1-alpine
    container_name: db
    networks:
      - ylabnetwork
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
  app:
    build:
      dockerfile: ./Dockerfile
    container_name: app
    networks:
      - ylabnetwork
    depends_on:
      - db
      - redis
    volumes:
      - type: bind
        source: ./admin
        target: /app/admin
    ports:
      - "8000:8000"
    env_file:
      - .env
    command:
      - uvicorn
      - menu_app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
    restart: always
  rabbitmq:
    image: rabbitmq:3.12.2-management-alpine
    container_name: rabbitmq
    networks:
      - ylabnetwork
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
  celery:
    build:
      context: .
    container_name: celery
    networks:
      - ylabnetwork
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./admin
        target: /app/admin
    depends_on:
      - rabbitmq
      - app
    command:
      - celery
      - --app=menu_app.worker:celery
      - worker
      - -B
      - -l
      - INFO
    restart: always

networks:
  ylabnetwork:
