version: "3.9"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    container_name: app
    external_links:
      - db:db
    ports:
      - "8000:8000"
    env_file:
      - .env
    command:
      - uvicorn
      - menu_app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
  db:
    image: postgres
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"