version: "3.9"

services:
  redis:
    image: redis
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
  db:
    image: postgres:15.1-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
    restart: always
  rabbitmq:
    image: rabbitmq
    container_name: rabbit
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    ports:
      - "5672:5672"
      - "15672:15672"
  beat:
    build:
      context: .
    container_name: beat
    depends_on:
      - rabbitmq
    command:
      - celery
      - "--app=menu_app.worker:celery"
      - beat
      - -l
      - INFO
    restart: always
  celery:
    build:
      context: .
    container_name: celery
    depends_on:
      - rabbitmq
    command:
      - celery
      - "--app=menu_app.worker:celery"
      - worker
      - -l
      - INFO
    restart: always
  app:
    build:
      dockerfile: ./Dockerfile
    container_name: app
    depends_on:
      - db
      - redis
    ports:
      - "8000:8000"
    env_file:
      - .env
    command:
      - uvicorn
      - menu_app.main:app
      - --host
      - "0.0.0.0"
      - --port
      - "8000"
      - --reload
    restart: always
