version: "3.9"

services:
  test_db:
    image: postgres:15.1-alpine
    container_name: test_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${TEST_DB}
      PORT: ${PORT}
      HOST_DB: ${TEST_HOST_DB}
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
  test:
    build:
      dockerfile: ./Dockerfile
    container_name: test
    env_file:
      - .env
    external_links:
      - test_db:test_db
    ports:
      - "8000:8000"
    command:
      - pytest
      - tests/unit
      - -v
