version: "3.9"

services:
  db:
    image: postgres:15.1-alpine
    container_name: db
    env_file:
      - .env
    ports:
      - "5432:5432"
  redis:
    image: redis
    container_name: redis
    env_file:
      - .env
    ports:
      - "6379:6379"
  test:
    build:
      dockerfile: ./Dockerfile
    container_name: test
    env_file:
      - .env
    external_links:
      - db:db
    ports:
      - "8000:8000"
    command:
      - pytest
      - tests/unit
      - -v
